Template params can only have one argument
reactphp/dns pull request #212
Opened 2023-01-21 14:29 UTC by WyriHaximus

The fact that a promise can also be rejected with a Throwable and/or Exception is implied and there is no need to also define that here.

Refs: https://github.com/reactphp/promise/pull/223

2023-01-24 11:54 UTC, SimonFrings approved these changes

2023-01-24 13:44 UTC, clue requested changes
Just noticed this should also be applied to the README documentation. @WyriHaximus is this something you can look into? :+1:

2023-01-24 16:07 UTC, WyriHaximus commented
> Just noticed this should also be applied to the README documentation. @WyriHaximus is this something you can look into? +1

@clue Just updated the README documentation and amended those changes to this PR.

2023-01-25 06:27 UTC, SimonFrings approved these changes

2023-01-25 12:38 UTC, clue approved these changes

2023-01-25 12:38 UTC, merged